version: '3.9'

services:
  backend:
    build: ./backend
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./static:/app/static

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
      - ./sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql:ro

  frontend:
    build: ./frontend
    container_name: react-ts-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:
    driver: local