version: '3.9'

services:
  backend:
    build: ./backend
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  frontend:
    build: ./frontend
    container_name: react-ts-app
    ports:
      - "3000:80"

volumes:
  postgres-data:
    driver: local